version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy to CircleCI
          command: |
            echo "Deploying to CircleCI..."
            # Add your deployment script here

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
