"use client";

import { useState } from 'react';
import { motion } from 'framer-motion';
import { FaArrowLeft, FaRobot } from 'react-icons/fa';
import AITestForm from './components/AITestForm';

interface AITestsPageProps {
  onBack: () => void;
}

export default function AITestsPage({ onBack }: AITestsPageProps) {
  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <motion.button
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={onBack}
          className="flex items-center text-gray-400 hover:text-white mb-8"
        >
          <FaArrowLeft className="mr-2" />
          Back to Options
        </motion.button>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-block p-4 rounded-2xl bg-gradient-to-r from-[#fcba28]/20 to-[#fcd978]/20 backdrop-blur-sm mb-6">
            <FaRobot className="w-12 h-12 text-[#fcba28]" />
          </div>
          
          <h1 className="text-4xl font-bold mb-4 bg-gradient-to-r from-[#fcba28] via-[#fcd978] to-[#fcba28] text-transparent bg-clip-text">
            AI-Generated Practice Tests
          </h1>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Get personalized practice tests generated by our AI system based on your preferences and skill level
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="max-w-3xl mx-auto"
        >
          <AITestForm />
        </motion.div>

        {/* Features */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="max-w-4xl mx-auto mt-16 grid md:grid-cols-3 gap-8"
        >
          {[
            {
              title: 'Personalized Content',
              description: 'Tests tailored to your skill level and learning goals'
            },
            {
              title: 'Real-time Generation',
              description: 'Get unique tests generated instantly by our AI system'
            },
            {
              title: 'Adaptive Learning',
              description: 'Questions adapt based on your performance and feedback'
            }
          ].map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 + index * 0.1 }}
              className="p-6 rounded-xl bg-white/5 border border-white/10 backdrop-blur-sm"
            >
              <h3 className="text-lg font-semibold text-[#fcba28] mb-2">{feature.title}</h3>
              <p className="text-gray-400">{feature.description}</p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </div>
  );
}
